simple.reg <- vector("numeric",0)
simple.reg <- c(simple.reg, lm.zn$coefficient[2])
simple.reg <- c(simple.reg, lm.indus$coefficient[2])
simple.reg <- c(simple.reg, fit.chas$coefficient[2])
simple.reg <- c(simple.reg, lm.nox$coefficient[2])
simple.reg <- c(simple.reg, lm.rm$coefficient[2])
simple.reg <- c(simple.reg, lm.age$coefficient[2])
simple.reg <- c(simple.reg, lm.dis$coefficient[2])
simple.reg <- c(simple.reg, lm.rad$coefficient[2])
simple.reg <- c(simple.reg, lm.tax$coefficient[2])
simple.reg <- c(simple.reg, lm.ptratio$coefficient[2])
simple.reg <- c(simple.reg, lm.black$coefficient[2])
simple.reg <- c(simple.reg, lm.lstat$coefficient[2])
simple.reg <- c(simple.reg, lm.medv$coefficient[2])
mult.reg <- vector("numeric", 0)
mult.reg <- c(mult.reg, lm.all$coefficients)
mult.reg <- mult.reg[-1]
plot(simple.reg, mult.reg, col = "green")
cor(Boston[-c(1, 4)])