avisos<- scan("G:/sigmod data/sigmod_title.txt", what="character", sep="\n")
avisos1 <- tolower(avisos)
avisos2 <- strsplit(avisos1, "\\W")
avisos3 <- unlist(avisos2)
avisos4<-removeWords(avisos3, stopwords("english"))
freq<-table(avisos4)
freq1<-sort(freq, decreasing=TRUE)
temple.sorted.table<-paste(names(freq1))
cat("Word", temple.sorted.table, file="G:/sigmod data/sigmod_id3.txt", sep="\n")